### ISSUE TITLE
Manual patch to fix Skill settings upload/ download after 19.08

### ISSUE THREAD

**Issue by FloatingBoater** [openhab/openhab-mycroft#74]
Hi,

After upgrading to 19.08, Mycroft stopped talking to OpenHAB, so after some light debugging, and a post on the forum, I'd like to contribute back the fixes.

Details are here:
https://community.mycroft.ai/t/openhab-skill-enhancement-to-use-skill-settings-fails/7383

In summary:
1. In `__init__.py.orig`, move def initialize(self): from line 67 to 51, moving the MycroftSkill methods into `initialize()`, leaving only `super()`.

2. Add double quotes and value tags to all entries in `settingsmeta.yaml`
```
name: openHAB
skillMetadata:
  sections:
    - name: Connection
      fields:
        - name: host
          type: text
          label: "OpenHAB server IP"
          value: "localhost"
        - name: port
          type: number
          label: "OpenHAB server port"
          value: "8080"
```
